### PR TITLE
cognito authorization using already configured cognito user pool 

### PR DESCRIPTION
**Pull request by dnvriend**
Deploys API secured with cognito user pool that is already configured by hand in your AWS account and region. Please create the necessary wiring to make the ARN configurable. 

Design: is it possible to do the following:
- Cognito can be configured manually, no need to do this using sbt-sam,
- Have an serverless-api resource configuration (typesafe config?)
- Have the serverless-api have an optional ARN of the cognito user pool
- If sbt-sam detects the cognito arn (some), it will enable the security items in swagger, and set the configured cognito user pool arn, effectively securing the API using tokens
- If the cognito user pool arn has not been set (none), it will not enable the secutity items in swagger, thus having an non-secured public API

### CODE REVIEW

**Comment by martijnvdgrift** [comment]
Hi @dnvriend, I'm already working on some cognito related code, shall I merge this branch with my own?

**Comment by dnvriend** [comment]
@martijnvdgrift only if it makes sense to do so. The gist of the PR is that the 'securityDefinitions' has been moved from the `Serverless::API` definition to the `swagger` definition.

**Comment by martijnvdgrift** [comment]
Yea Agreed, probably it makes more sense to just rebase my branch lol

**Comment by dnvriend** [comment]
@martijnvdgrift you really need to teach me how to rebase :)

**Pull request merged**
